# Generated by Django 5.0.7 on 2024-07-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_productimage_product_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
