# Generated by Django 5.0.7 on 2024-08-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('WALLET', 'Wallet'), ('COD', 'Cash on Delivery')], default='COD', max_length=20),
        ),
    ]
